[versions]
coroutines = "1.10.1"
junit-jupiter = "5.10.2"
logback = "1.5.15"
slf4j = "2.0.16"

[libraries]
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }


[plugins]
jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.1.0" }
